[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "resume_radar"
version = "0.1.0"
description = "AI-powered CV reviewer"
authors = [{ name = "Iain Clark" }]
dependencies = []
